### ISSUE TITLE
FileHelpers pulls excel dlls that are not need for the basic scenarios

### ISSUE THREAD

**Issue by regisbsb** [MarcosMeli/FileHelpers#111]
Installing a library like Rhino-Etl pulls in FileHelpers which is pulling in FileHelpers.Excel* and office interops. We shouldn't need this for the basic pipeline.

Is it possible to split the packages? Thanks.

https://github.com/hibernating-rhinos/rhino-etl/issues/12

**Comment by MarcosMeli** [comment]
I change the rhino-etl source pointing to new version of the library

https://github.com/hibernating-rhinos/rhino-etl/pull/23
