### ISSUE TITLE
Exception when using DelimitedClassBuilder. 

### ISSUE THREAD

**Issue by motime** [MarcosMeli/FileHelpers#112]
Hi,

I am trying to create the dynamic delimited record using this code:

            var classBuilder = new DelimitedClassBuilder("cls_" + Guid.NewGuid().ToString("N"), ",")
            {
                Namespace = "ns_" + Guid.NewGuid().ToString("N"),
                IgnoreFirstLines = 0,
                IgnoreEmptyLines = false
            };
          
            m_Context.Mappings.ForEach(map =>
            {
                string name = map.Name;
                Type type = map.Type ?? typeof (string);
                var field = classBuilder.AddField(name, type);  
            });

            var recordClass = classBuilder.CreateRecordClass();

It fails on some servers with, throwing this exception:

Failed to create pipeline SomeEtlProcess: Error Compiling Expression: 
Line 0: An assembly with the same simple name 'SomeAssembly, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null has already been imported. Try removing one of the references or sign them to enable side-by-side.

The class does not use SomeAssembly (types are alwayes primitives)

I am using version 3.0.46-beta.

Any ideas?

TIA, 
Moti.

**Comment by MarcosMeli** [comment]
Hi there Moti

Are calling multiple times to CreateRecordClass ?

What about calling CreateEngine or the other methods, I will review the code to check if it tries to compile it multiple times

Thanks

**Comment by motime** [comment]
Hi,

Not in the same instance.

The process is the usual ETL. Client uploads file, maps it, I create the record class and use it.
On the server where it fails, it fails every single time. On local development environment it works.

Thank you,
Moti

**Comment by MarcosMeli** [comment]
Hi Moti I just made a change that must fix your problem, now the library only load system assemblies and no all the referenced in the Current Domain

Can you try with the last version: http://teamcity.codebetter.com/viewLog.html?buildId=195459&buildTypeId=FileHelpersMaster&tab=artifacts

Can you confirm that it works ?

Thanks

**Comment by motime** [comment]
Thank you, I will know in a couple of days.

**Comment by MarcosMeli** [comment]
Great, please after you test it, add your comments below

**Comment by motime** [comment]
Hi Marcos,

It seems to be working now.

Thank you very much.

**Comment by MarcosMeli** [comment]
Happy that works now :)

Thanks for reporting
Marcos
