### ISSUE TITLE
WebSite proof-read and review

### ISSUE THREAD

**Issue by MarcosMeli** [MarcosMeli/FileHelpers#117]
You can check the new Home of the library www.filehelpers.net

Spellcheck it and correct some grammar.

You must clone the gh-pages branch:
https://github.com/MarcosMeli/FileHelpers/tree/gh-pages

Or use the Edit Icon in the upper right margin of the pages, edit the contents online and send a pull request :+1:

**Comment by jboyer2012** [comment]
@MarcosMeli I can take a look at the page for you. I'll send a pull request with any changes.

**Comment by MarcosMeli** [comment]
Great @jboyer2012 !!!

You can just use the edit button in the upper right corner of each page to make changes

Thanks !!

**Comment by maybebored** [comment]
Is this issue still active

**Comment by mcavigelli** [comment]
The website got already many grammar fixes and typos.
Although not being a native English writer / speaker, I will close it now 😉

Do not hesitate to send us fixes or pull requests.

Thank you, Matthias
