### ISSUE TITLE
Get rid of the culture-dependent DateTime parsing

### ISSUE THREAD

**Issue by eugeneavry** [MarcosMeli/FileHelpers#123]
FileHelpers.ConvertHelpers.DateTimeConverter is vulnerable to culture changes on the thread running the parsing. This makes the entire code very brittle. At least, exception messages prove to be misleading in this case.

**Comment by MarcosMeli** [comment]
We are discussing this issue in the pull request #124

**Comment by MarcosMeli** [comment]
Closed with the Pull Request #128
Thanks for the feedback !!
