### ISSUE TITLE
Usage of System.Data.SqlClient requires Xamarin License

### ISSUE THREAD

**Issue by MarcusRiemer** [MarcosMeli/FileHelpers#154]
I would like to use the CSV parsing to allow bulk data import into a Xamarin app. Sadly I only have the Indie Version of Xamarin, which forbids the usage of `System.Data.SqlClient`. Would it be possibe to somehow remove that functionally in a mobile build? There is a more or less undocumented `__MOBILE__` preprocessor directive that could be used to omit that reference.

**Comment by MarcosMeli** [comment]
Hi @MarcusRiemer can you check this build:

http://www.filedropper.com/filehelpersnodatalink

It has no Datalink feature, so no SqlClient Usage.

I don't do mobile programming with Xamarin, but if you help me I have no problem to make the lib mobile compatible, and optimize it

Thanks

**Comment by MarcosMeli** [comment]
@MarcusRiemer Any news about the version I uploaded ?

Thanks

**Comment by mcavigelli** [comment]
Since release 3.3 we ship a net standard 2.0 binary.
That should solve your problem.

Matthias
