### ISSUE TITLE
Removing last field from options does not reset the lastField property

### ISSUE THREAD

**Issue by pradu71** [MarcosMeli/FileHelpers#157]
Removing last field in a record, then reading all records generates an exception

    engine.Options.RemoveField("Digitale")
    Dim records = engine.ReadFile(fn)

    FileHelpers.FileHelpersException: Line: 1 Column: 207. Delimiter ';' not found after field 'CDC' 
    (the record has less fields, the delimiter is wrong or the next field must be marked as optional).

When removing any field from the Fields array of RecordInfo should reset the lastField property of the last item in the array:

    // in Core/RecordInfo.Factory.cs 
    public void RemoveField(string fieldname)
        {
            var index = GetFieldIndex(fieldname);
            Fields[index] = null;
            Fields = Array.FindAll(Fields, x => x != null);
            Fields[Fields.Length - 1].IsLast = true; // HERE <====
        }

**Comment by MarcosMeli** [comment]
@pradu71 Thanks for the feedback !!

I just reimplementd IsLast IsFirst and change the RemoveField

https://github.com/MarcosMeli/FileHelpers/commit/bc19bb04731ae157d20a22d6fcdeeaa63f9ae2c2

I will try to make a build so you can test it, what .net version are you using ?

**Comment by pradu71** [comment]
.net 4.0

**Comment by MarcosMeli** [comment]
Thanks, I will commit some other changes in some minutes to make tests pass

**Comment by MarcosMeli** [comment]
You can download the build from here:

http://teamcity.codebetter.com/viewLog.html?buildId=198119&buildTypeId=FileHelpersMaster&tab=artifacts

Let me know if it works now

**Comment by pradu71** [comment]
works with this build.

**Comment by MarcosMeli** [comment]
I will release a new version at least as RC via NuGet
