### ISSUE TITLE
INotifyRead Don't work with MultiRecordEngine?

### ISSUE THREAD

**Issue by michel-soares** [MarcosMeli/FileHelpers#167]
INotifyRead Don't work with MultiRecordEngine?

**Comment by cfasilva** [comment]
Hi friend, some answer about it?

**Comment by benjcallaghan** [comment]
I don't know exactly what your situation is. Could you provide more details?

I ran into a scenario where it appeared INotifyRead wasn't working with a MultiRecordEngine. I had three types being passed in, and only the second implemented INotifyRead. Apparently, the flag that determines if read/write events should be fired only uses the first type passed into the MultiRecordEngine. I rearranged the types so the INotifyRead type was first. Then I started getting errors that my other two did not implement INotifyRead. The workaround was to implement INotifyRead on all of my types.

Suggestion:
Please update the MultiRecordEngine so it dynamically checks for the INotifyRead/INotifyWrite interfaces on every type. This should not be an all-or-nothing solution.

**Comment by bcallaghan-et** [comment]
Has any progress been made on this issue? I'm still facing it today.

**Comment by mcavigelli** [comment]
This is same as #401.
