### ISSUE TITLE
Filehelpers Version for .Net 3.5 references 4.0 framework

### ISSUE THREAD

**Issue by binfish** [MarcosMeli/FileHelpers#168]
I am working on a .Net 3.5 project.
Trying to reference **filehelpers.dll** from directory **FileHelpers_3.1.5_Build\Lib\net35** (from latest zip) results in a warning: (troughly translated from German) _"filehelpers.dll or another dependency need a later version of .Net Framework as stated in project"_.
Looking into the dll (_dot.peek_) it says : **msil, .Net Framework v4.0**

Where do I find the .Net-3.5 Version?

Thanks
Clemens

**Comment by mcavigelli** [comment]
Hello Clemens
I can confirm the described behavior. I might look into this issue, but cannot give you any guarantee when and if it will be fixed.

However the version in Lib/net20 (in nuget package) references the .Net Framework v2.0:
It should be possible to use that version in your .Net 3.5 project.

Does this allow to continue with your work for the moment?
Matthias

**Comment by binfish** [comment]
Thanks for verifying. I successfully use *Lib/net20* for now.

**Comment by mcavigelli** [comment]
* Packaging is fixed on stable branch.
* On master we need to see how we can support .Net Framework 2.0 (the one from 2005 :-)), as we now have linq code (only working from .Net Framework 3.5 on) in it.
