### ISSUE TITLE
Not compatible with DNX Core 5.0

### ISSUE THREAD

**Issue by Polarbeerx** [MarcosMeli/FileHelpers#185]
Running release candidate 1 for DNX Core 5.0 and Filehelpers is not compatible.

The following error msg is given in VS2015:

The dependency FileHelpers 3.1.5 in project DataLayer does not support framework DNXCore,Version=v5.0

**Comment by neumann1990** [comment]
Sounds like FileHelpers is not compatible with .NetCore yet (#213)

**Comment by mcavigelli** [comment]
Closing issue. Is being duplicated by #213 as mentioned by @neumann1990.
