### ISSUE TITLE
FileHelperAsyncEngine does not behave corretly when using as IEnumerator of T

### ISSUE THREAD

**Issue by legezam** [MarcosMeli/FileHelpers#186]
According to the C# specification (https://msdn.microsoft.com/en-us/library/system.collections.ienumerator.movenext%28v=vs.110%29.aspx#Anchor_2), the MoveNext method of the enumerator should return false when it has reached the end of the sequence. Any subsequent call for this method should return false until reset is called.

However, there is something with Options.IgnoreFirstLines, because if it is set explicitly, FileHelperAsyncEngine.MoveNext can be called only once when it reached the end of the sequence. Subsequent calls throw BadUsageException {"Before call ReadNext you must call BeginReadFile or BeginReadStream."}.

The issue can be reproduced with this code snippet:
```C#
   public class Program
  {
    [DelimitedRecord(",")]
    public class Record
    {
      public string Id;
      public string Name;
    }

    static void Main(string[] args)
    {
      var engine = new FileHelperAsyncEngine<Record>();
      string src = "should,beignored\nabc,JohnDoe";
      engine.Options.IgnoreFirstLines = 1;
      using (engine.BeginReadString(src))
      {
        var enumerator = (engine as IEnumerable<Record>).GetEnumerator();
        enumerator.MoveNext();
        enumerator.MoveNext();
        enumerator.MoveNext();
      }
    }
  }
```

If i put the ignore into the using, the issue is gone but a new one rises: the first line is not ignored:
```C#
  public class Program
  {
    [DelimitedRecord(",")]
    public class Record
    {
      public string Id;
      public string Name;
    }

    static void Main(string[] args)
    {
      var engine = new FileHelperAsyncEngine<Record>();
      string src = "should,beignored\nabc,JohnDoe";
      using (engine.BeginReadString(src))
      {
        engine.Options.IgnoreFirstLines = 1;
        var enumerator = (engine as IEnumerable<Record>).GetEnumerator();
        enumerator.MoveNext();
        enumerator.MoveNext();
        enumerator.MoveNext();
      }
    }
  }
```

**Comment by legezam** [comment]
Just realized it has nothing to do with ignorelines, it just shifts the fail with one call. In the second example, the 4th call to MoveNext would fail.

**Comment by MarcosMeli** [comment]
I just added this code to avoid the problem, thanks for found the issue and provided an example.

Is so easy to fix the problems that way 

Thanks !!
