### ISSUE TITLE
Have to flush the text writer after WriteStream.

### ISSUE THREAD

**Issue by Iukekini** [MarcosMeli/FileHelpers#190]
You have to flush the text writer after calling WriteSteam or you will end up with an incomplete stream.

**Comment by mcavigelli** [comment]
Hello lukekini

Text writers and streams are used in several places in FileHelpers.
And your statement is very general.

The following would help us considerably:

1. Indicate where the text writer and stream handling is erroneous.
2. Describe which methods and types of the library you use, how the library behaves and what your expectation is.

Thank you for supporting us, Matthias

**Comment by mcavigelli** [comment]
Hello lukekini

Is there any chance that you can show us where the problem is? Is the problem similar to
http://stackoverflow.com/questions/40119550/filehelpers-writestream-only-writing-the-first-2048-characters-to-output/40119574#40119574 ?

**Comment by mcavigelli** [comment]
Seems that we have to verify the behavior by ourselves.
Hopefully we get some support from Code Analyze / FxCop.

**Comment by MarcosMeli** [comment]
The FileHelperEngine write the stream in a using statement, so it will auto close and flush the stream

If you use the FileHelperAsyncEngine you MUST call the Close method or better yet use the using statement

```
using(engine.BeginWriteFile("TestOut.txt"))
{
    foreach(Customer cust in arrayCustomers)
    {
        engine.WriteNext(cust);
    }
}
```
http://www.filehelpers.net/docs/html/M_FileHelpers_FileHelperAsyncEngine_1_Close.htm

@Iukekini do you have more info about this problem ?
