### ISSUE TITLE
Fixed Length Specify Column Location

### ISSUE THREAD

**Issue by iamwyza** [MarcosMeli/FileHelpers#202]
I needed to parse a Fixed Width file, however, it appears that FH assumes that the field is contiguous. Meaning that there are no places where there is no data in a row. For example, you could have a file with 5 "fields". Field 1 is column 0-10, Filed 2 is 11-20, Field 3 is 25-30, Field 4 is 33-40, and Field 5 is 45-50. The spaces between 21 and 24, 31-32, and 41-44 shouldn't be parsed. As they are reserved by the file provider for future use. Is there a plan or way to say that in a fixed width field we can specify start/end positions instead of field length?

**Comment by michaelakin** [comment]
You could do like the old days and create "filler" fields for a specific length.  

`[FieldFixedLength(4)]`
`public string Filler3a`

**Comment by MarcosMeli** [comment]
Like @michaelakin said you must use some filler field, also I recomend to use private for the field and the attribute [FieldValueDiscarded]

```cs
[FieldFixedLength(4)]
[FieldValueDiscarded]
private string Filler3a
```

**Comment by iamwyza** [comment]
Yes, you _could_ do it that way, but that means you're going to litter your class with bad fields.  On files with hundreds of fields (which I've dealt with at least 3 of those so far), that's alot of garbage code.  FH has an internal pointer to the current position within a line.  Being able to move that internal pointer would easily solve this issue.  As far as I can tell, there is no reason you couldn't expose that pointer in the line class to be mutable.
