### ISSUE TITLE
Need the real line number when using IgnoreEmptyLines 

### ISSUE THREAD

**Issue by perrich** [MarcosMeli/FileHelpers#225]
Hi, 

If we use IgnoreEmptyLines and convert file to a DataTable, Array or List, the empty lines should be kept (for instance by creating an empty row or a null object) as we need the same structure as the original file.
Without it, we can't display a business issue with the correct line number in the file. 

The IgnoreFirst is not really a problem. But IgnoreEmptyLines does.

To keep backward compatibility, an option might be created to manualky enable this feature.
Seems that easy changes must be made in FileHelperEngine.ReadStreamAsList(TextReader reader, int maxRecords, DataTable dt). 
But before implement it / provide a pull requests, do you think it can be useful ?

**Comment by mcavigelli** [comment]
A solution has been discussed in the pull request #238.

Tests in the file RealLineNumber show how to achieve this by subscribing to the AfterReadEvent.
