### ISSUE TITLE
The type or namespace name 'FieldCaptionAttribute' could not be found

### ISSUE THREAD

**Issue by liupengf12** [MarcosMeli/FileHelpers#230]
I installed the FileHelpers v3.1.5 from Nuget:

`<package id="FileHelpers" version="3.1.5" targetFramework="net45" />`

Why the attribute "FieldCaptionAttribute" could not be found?

**Comment by mcavigelli** [comment]
Hello Peter

_FieldCaptionAttribute_ is only included in release _3.2.7_.
Release 3.2.7 is available through nuget from today on.

I hope this works for you, Matthias
