### ISSUE TITLE
Replace usages of Encoding.Default with Encoding.GetEncoding(0)

### ISSUE THREAD

**Issue by mcavigelli** [MarcosMeli/FileHelpers#239]
In order to get more .NET Standard 1.6 compatible (see #213), we would like to replace all usages of Encoding.Default with Encoding.GetEncoding(0). Encoding.GetEncoding(0) is present in .NET Standard 1.6 and the .NET Framework.

These changes must be included in the master branch.

**Comment by guillaumejay** [comment]
I'd like to start on this one : since I'm not used to collaborate on open source project on github, I'd rather start on something easy.

**Comment by mcavigelli** [comment]
Salut Guillaume

Thank you for helping us. It seems that we cannot assign the issue to you by setting the assignee property. So we just write it down as as a comment.

Assigned to @guillaumejay.

Looking forward to your pull request, Matthias

**Comment by guillaumejay** [comment]
Weird, I've been assigned on issue on another (private) github project without any trouble...

Looking forward to my first request :)

**Comment by MarcosMeli** [comment]
Looks like you must be added as collaborator,
Github don't let me do it
