### ISSUE TITLE
FileAccess.Read & FileShare.Read

### ISSUE THREAD

**Issue by iamwyza** [MarcosMeli/FileHelpers#248]
Any chance to have the option to tell FileHelpers engines to try to open a file with FileShare.Read and FileAccess.Read set?  Currently if the file is open by something else (say Excel) FH will fail because Excel locks the file.  It'd be nice to have the option of saying that we want to load the file even if it is locked (assuming whatever is locking it has set the appropriate sharing levels on its side).

Thanks

**Comment by iamwyza** [comment]
Edit: Changed FileShare.Read to FileShare.ReadWrite.  Excel appears to open files with Share level of ReadWrite, so Read fails.

**Comment by MarcosMeli** [comment]
Hi there you can pass an Stream to the engines and when creating the stream
you can use the right flags
Cheers

**Comment by iamwyza** [comment]
Oh, so you can.  Have been using the BeginReadFile method, didn't notice the BeginReadStream method.  Excellent.  Thanks!
