### ISSUE TITLE
Publish to nuget

### ISSUE THREAD

**Issue by pablotdv** [MarcosMeli/FileHelpers#259]
What's missing for publishing of the nuget package?
The Attributes already are accepting Property, but the version in nuget not.
What can I do to help?

**Comment by cigano** [comment]
Not all of them. Some of them, like [`FieldIgnoredAttribute`](https://github.com/MarcosMeli/FileHelpers/blob/master/FileHelpers/Attributes/FieldIgnoredAttribute.cs), only can be applied to fields. 

[There's a milestone defined here](https://github.com/MarcosMeli/FileHelpers/issues/67), but apparently is not ready yet.

**Comment by mcavigelli** [comment]
- [ ] Testing Excel package in alpha package on appveyor
- [ ] Publishing beta to nuget.org
- [ ] Publishing stable to nuget.org
- [ ] Creating release notest
- [ ] Update of filehelpers.net to version 3.2.6

**Comment by mcavigelli** [comment]
Hi Pablo

Thank you for offering your help to make the 3.2.6 release happen!

It would be very helpful, if you could test the Excel (Excel COM based, not NPOI based) nuget package.
1. Download and install it from https://ci.appveyor.com/nuget/filehelpers
2. Do some imports / exports maybe similar to
   FileHelpers/FileHelpers.Tests/Tests/DataLink/ExcelStorageTests.cs 

Let me know, if it worked for you!

Matthias

**Comment by mcavigelli** [comment]
Excel package unfortunately not running yet on computer with installed MS Excel.
I need to find out, what Excel / Interop version needs to be installed.

**Comment by cigano** [comment]
Matt,

Why don't you use EPPlus for Excel Generation, instead of Excel / Interop?
Excel / Interop is not good for Cloud Environments.

**Comment by mcavigelli** [comment]
Hi Cigano

Thank you for your comment: for compiling we used version 12, but the nuget package already referenced version 15. That did not work. Now the nuget package also references version 12.

We are aware of the problems that Excel / Interop presents.
For the release 3.2.6 I still want to keep the behaviour identic to release 3.1.5.

Matthias

**Comment by mcavigelli** [comment]
An alpha version (3.2.6-alpha) is available on nuget.org.
Let me know if it works for you or if you have any problems.

Thank you for your testing, Matthias

**Comment by mcavigelli** [comment]
Uploaded 3.2.7 final to nuget.org!

**Comment by mcavigelli** [comment]
Website is updated.

That was the release 3.2.7!
