### ISSUE TITLE
INotifyRead not working with ExcelNPOIStorage

### ISSUE THREAD

**Issue by DCSCardenass** [MarcosMeli/FileHelpers#263]
When I implement INotifyRead doesn't seem to work with ExcelNPOIStorage, the process ignore the BeforeRead and  AfterRead methods

This is the example I am using, I have a class User: this class implements the interface INotifyRead 

`    [DelimitedRecord("|")]
    public class User : INotifyRead
    {
        public string FirstName;
        public string LastName;

        [FieldConverter(ConverterKind.Date, "yyyyMMdd")]
        public DateTime mydate;

        public void AfterRead(AfterReadEventArgs e)
        {
        }

        public void BeforeRead(BeforeReadEventArgs e)
        {
            int x = e.LineNumber;
        }
    }`

**Comment by netniV** [comment]
ExcelStorageBase which is inherited by ExcelNPOIStorage does not implement the filehelper INotify interfaces.  In fact, it doesn't implement the older BeforeRecord/AfterRecord style events either.

**Comment by mcavigelli** [comment]
Yes, the behaviour is as expected and as commented by @netniV .

I have added a hint on the examples (on website on next publish of the documentation, depends on #385) and the interfaces INotifyRead and INotifyWrite.
