### ISSUE TITLE
getting Could not load file or assembly 'FileHelpers, Version=3.1.5.0, Culture=neutral, PublicKeyToken=3e0c08d59cc3d657' or one of its dependencies. in Azure Functions Project

### ISSUE THREAD

**Issue by Schenz** [MarcosMeli/FileHelpers#264]
I had used this library to read a Fixed Length file in an Azure WebJob in the past, and now in the process of converting to an Azure Function (serverless), but using the same code as before I'm now getting a Could not load file or assembly 'FileHelpers, Version=3.1.5.0, Culture=neutral, PublicKeyToken=3e0c08d59cc3d657' or one of its dependencies.

internal static List<XElement> ReadPositionalFile(Stream stream, UploadMessage uploadMessage, IList<FileDefinitionColumn> fileDefinitionColumns)
        {
            TextReader tr = new StreamReader(stream);

            var positionalRows = fileDefinitionColumns.OrderBy(d => d.StartPosition ?? 0);

            //Create Dynamic class based on Specs above
            var cb = GetSpecClass(positionalRows);

            //Create FileHelpers engine instance
            var engine = new FileHelperEngine(cb.CreateRecordClass()); //Exception Happens here

            //Read file data into Data table
            var dtImportData = engine.ReadStreamAsDT(tr);

            var delimitedColumns = fileDefinitionColumns.OrderBy(d => d.StartPosition ?? 0);
            var distinctRows = new List<FileDefinitionColumn>();

            foreach (var fileDefinitionColumn in from fileDefinitionColumn in delimitedColumns
                                                 let found = distinctRows.Any(definitionColumn => definitionColumn.Name == fileDefinitionColumn.Name)
                                                 where !found
                                                 select fileDefinitionColumn)
            {
                distinctRows.Add(fileDefinitionColumn);
            }

            var elements = from DataRow row in dtImportData.Rows
                           select AddToRowList(row, uploadMessage, distinctRows);

            return elements.Distinct().ToList();
        }

**Comment by mcavigelli** [comment]
Since version 3.3.0 we ship a part of FileHelpers as a .NET Standard 2.0 library. https://github.com/MarcosMeli/FileHelpers/releases/tag/3.3.0
I assume that version works on Azure.

I guess you use a `ClassBuilder`in method `GetSpecClass` : that class is not contained in the .NET Standard library. https://github.com/MarcosMeli/FileHelpers#current-support-for-net-standard--net-core
