### ISSUE TITLE
.NET core compatibility

### ISSUE THREAD

**Issue by mcheruvu** [MarcosMeli/FileHelpers#275]
Hello

I would like to know whether FileHelpers is compatible with .NET core. I have touch time finding this information as it does mention anywhere explicitly.

Thanks

**Comment by netniV** [comment]
I am not sure but one of the major differences I've seen between .NET Core and .NET Framework is that core does not return full type information when you do `object.GetType()` so you also have to do `object.GetTypeInfo()`

Unfortunately, when I cloned the repo and then searched for GetTypeInfo() the only project that had this in was the FileHelpers.Analyzer project.  Which would lead me to suspect that is the only .NET Core project so far.

There is always a chance I may be wrong though as I'm just a developer whose looked at a couple of issue with the project, not one of the original developers.

**Comment by netniV** [comment]
Oh, I have just noticed that there is in fact a .NET Core branch within the GitHit Repo.  I have no idea if that is completed work etc, but you could try checking that out.

**Comment by mcavigelli** [comment]
We have published an alpha release of FileHelpers dll, targeting directly .NET Core 2.0.
See https://github.com/marcosmeli/filehelpers#current-support-for-net-core for some comments on it.

Please let us know, if that release works for you.

Matthias Cavigelli

**Comment by mcavigelli** [comment]
With pullrequest #295 we are targeting .NET Standard 2.0!

**Comment by jfantunes** [comment]
Regarding to dynamic methods is there any chance to use it on .net standard?
