### ISSUE TITLE
.NET Standard 2.0 compatible

### ISSUE THREAD

**Issue by rjmille2** [MarcosMeli/FileHelpers#279]
I'm trying to reference FileHelpers in a .NET Standard 2.0 compatible library.  Are there plans to convert FileHelpers to .NET Core 2.x?

**Comment by mcavigelli** [comment]
We have published an alpha release of FileHelpers dll, target directly .NET Core 2.0.
See https://github.com/marcosmeli/filehelpers#current-support-for-net-core

Please let us know, if that release works for you.

Matthias Cavigelli

**Comment by mcavigelli** [comment]
With pullrequest #295 we are targeting .NET Standard 2.0!
