### ISSUE TITLE
Thread safety of FileHelperEngine when using it in TPL

### ISSUE THREAD

**Issue by pantonis** [MarcosMeli/FileHelpers#290]
Hi,

I have a question as to whether FileHelperEngine is thread safe when using with TPL or Parallel.ForEach
See below my sample code:

```
var engine = new FileHelperEngine<MyClass>();
Parallel.ForEach(allData, (data) =>
{
      engine.ReadString(data);
});
```
Can engine be shared across multiple threads?

Thanks

**Comment by mcavigelli** [comment]
Hi pantonis

I kindly ask you to use Stackoverflow for questions.
https://stackoverflow.com/tags/filehelpers

Thank you for considering using FileHelpers.
Matthias
