### ISSUE TITLE
Problem in NuGet package?

### ISSUE THREAD

**Issue by lscorcia** [MarcosMeli/FileHelpers#301]
Hi,
I'm moving the dependencies for one of my .net 3.5 projects (SharePoint 2010...) to NuGet and discovered that the v3.1.2 NuGet package does not contain the assembly for .net 3.5. 

From the docs I see that .net 3.5 support was dropped in the latest release, but I should still be able to use the previous versions in my project, right?

Thanks for your help,
Luca

**Comment by mcavigelli** [comment]
Buona sera Luca

Release 3.2.7 is the last one currently supporting .NET Framework 3.5:
Download: https://www.nuget.org/packages/FileHelpers/3.2.7
Release notes: https://github.com/MarcosMeli/FileHelpers/releases/tag/3.2.7

Saluti, Matthias

**Comment by lscorcia** [comment]
Sorry, you are completely right. I think I had somewhat messed up my project yesterday since Visual Studio was reporting that the package didn't contain any compatible version of the library. Tried again today and everything is working fine.

Grazie mille per l'aiuto e buona serata! 
Ciao! :)
