### ISSUE TITLE
Reading Txt file

### ISSUE THREAD

**Issue by ertugrulkaya** [MarcosMeli/FileHelpers#303]
Dear All,

I want to read 10000 rows in txt file .  When I  use delimiter '|' char, some rows doesn't have the char. so that I don't want to read any rows without '|' delimiter char.

How can do it ? 

Thank you?

**Comment by mcavigelli** [comment]
I kindly ask you to use Stackoverflow for questions.
https://stackoverflow.com/tags/filehelpers

Thank you for considering using FileHelpers.
Matthias
