### ISSUE TITLE
is it possible to push out a new version of 2.9.9 to nuget?

### ISSUE THREAD

**Issue by jamesmanning** [MarcosMeli/FileHelpers#31]
Currently there are a fair number of fixes that are available on github but not from the NuGet versions.  It's possible to work around by cloning from github and building there and using the result, but especially for use cases like LINQPad scripts (where LINQPad has built-in NuGet integration), it would be far nicer to have a recent version on NuGet.

Making it available as a pre-release version of 3.0.0 would be an option, if there are already breaking changes and what's currently checked in can't/shouldn't be released without the major version change.

Thanks!

**Comment by jbparker** [comment]
Hey @MarcosMeli 

Would it be possible to create a package for [the stable build](http://teamcity.codebetter.com/viewType.html?buildTypeId=FileHelpersStable) in addition to the alpha release based on the development branch?

I'm wanting to update one of my company's applications using FileHelpers (thank you for this library, by the way!) from 2.0 to the latest stable build, but the [stable package on NuGet](https://www.nuget.org/packages/FileHelpers-Stable/) is old (as @jamesmanning indicated) - it has a fair number of downloads but it doesn't look to be official (and is from 2011).

If there are potential issues in the current development branch (and the alpha package), I'd prefer to steer clear for now until it's ready for production.

Thanks!

**Comment by jbparker** [comment]
@MarcosMeli
One thought on the prerelease NuGet packages - can we do a [NuGet Publish](https://confluence.jetbrains.com/display/TCD8/NuGet+Publish) build step in the TeamCity configuration when the build is successful (all tests pass & NuGet packages generated)?

Thanks!

**Comment by MarcosMeli** [comment]
The stable package was created a time ago, I forgot to close this issue

https://www.nuget.org/packages/FileHelpers/

Scroll down to version history
