### ISSUE TITLE
Using Fluent Validation with File Helpers

### ISSUE THREAD

**Issue by davidbuckleyni** [MarcosMeli/FileHelpers#329]
Normally I would use Fluent validation for any imports but I was wondering was there a way to do this in Filehelper by that I mean using the validation in relation to FluentValidation on the engine class ?.

https://github.com/JeremySkinner/FluentValidation

I would love the ability to re use this without having to do re do my validation routines.

**Comment by mcavigelli** [comment]
Hi David

I don't know FluentValidation. It seems to me, that it is working in a totally different domain than FileHelpers. I assume you just do your imports and then do the validations on the created objects with FluentValidation.

Matthias
