### ISSUE TITLE
In Nuget 3.4, the namespace FileHelpers.Dynamic is missing

### ISSUE THREAD

**Issue by dark-yak** [MarcosMeli/FileHelpers#340]
In the version 3.3 and 3.4 of the Nuget packages, the namespace FileHelpers.Dynamic is missing from the project.
![image](https://user-images.githubusercontent.com/30153784/54937309-74e39680-4f24-11e9-865a-a0f4196a9af9.png)

I don't know if it is by design and if this namespace is deprecated ?

François

**Comment by mcavigelli** [comment]
It is by design, see https://github.com/MarcosMeli/FileHelpers#current-support-for-net-standard--net-core

Merci, Matthias
