### ISSUE TITLE
InternalStreamReader FileAccess to ReadWrite

### ISSUE THREAD

**Issue by LordPinhead** [MarcosMeli/FileHelpers#343]
Based on Issue #248, is there a reason not to change the FileStream Constructor to use FileShare.ReadWrite? I know i could use a Stream directly to avoid errors while Excel locks the file, but i whould think Reading should not be stopped because someone forgot to close the file. I try´d it with this Option and have no negative impacts  other than "The File could be changed by Excel while reading", that is the only downside i can think of.

**Comment by netniV** [comment]
> @LordPinhead: I have an workaround with an FileStream an StreamAccess ReadWrite, so i can open it. I opened an Issue on Github to ask if there is any reason not doing this by default.
> ```
> using (var stream = new FileStream(DataFile.FullName, FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
>   using (var reader = new StreamReader(stream)) {
>     engine.ReadStream(reader).ToList().ForEach(record => {
>       // Do Something
>     });
>   }
```
I'll be honest, I'm surprised that works given that Excel has a write lock already on it. My text editors that handle locking (marking the file as readonly) for most scenarios won't even open an Excel locked file. 

`FileShare.Read` is the default for those `FileStream` constructors without a `FileShare` parameter so maybe they aren't specifying it either. 

The only concern I would have is when another process has the ability to write to a file we are trying to read, that could lead to data corruption issues in what we are trying to read.  So given this I, personally, wouldn't feel it's correct use that by default in most scenario's.

**Comment by mcavigelli** [comment]
I'm not sure if I understand the suggestion: are you suggesting to change
https://github.com/MarcosMeli/FileHelpers/blob/9b063df0993f66c227a56fd3f675c3cd4161f42c/FileHelpers/Streams/InternalStreamReader.cs#L56

            var stream = new FileStream(path,
                FileMode.Open,
                FileAccess.Read, 
                FileShare.Read,
                bufferSize,
                FileOptions.SequentialScan);

            // change
            var stream = new FileStream(path,
                FileMode.Open,
                FileAccess.ReadWrite,
                FileShare.Read,
                bufferSize,
                FileOptions.SequentialScan);

Matthias

**Comment by netniV** [comment]
No, I think he was after the row below, FileShare to be read/write, so that other files can have a write lock.

**Comment by mcavigelli** [comment]
Thank you for your clarification. It now changed included.
