### ISSUE TITLE
FileHelpers.Dynamic missing in 3.4.1? 

### ISSUE THREAD

**Issue by jphellemons** [MarcosMeli/FileHelpers#358]
As I have read here https://github.com/MarcosMeli/FileHelpers/issues/340

and in the readme:
Dynamic: ClassBuilder and CsvClassBuilder. ClassBuilder is difficult to maintain and a rewrite in .NET Core / Standard as is, would require to reference three NuGet packages. There must be better ways to write record structures at runtime.

So I need to downgrade to something below 3.3 and run full framework to use a dynamic ordering of columns? Or is it something that will be brought back any time soon?

**Comment by martindalec** [comment]
I rewrote a chunk of the ClassBuilder to use Roslyn instead of System.CodeDom and now I've got dynamic class generation back in my .net core projects

**Comment by jkblue72** [comment]
I'm don't see the Dynamic classes in the netstandard2.0 version yet.  I'm looking that 3.4.2 alpha branch.  Is this checked-in somewhere else?

**Comment by mcavigelli** [comment]
For ClassBuilder and .NET Standard please see here
https://github.com/MarcosMeli/FileHelpers#current-support-for-net-standard--net-core

Matthias
