### ISSUE TITLE
Errors not available when using ErrorMode.IgnoreAndContinue with .ReadStream()

### ISSUE THREAD

**Issue by marcelfleeds** [MarcosMeli/FileHelpers#359]
Hello,
I'm using the latest version (4.3.1) of FileHelpers and I receive a FileStream from my database.
I receive a FileStream from my database and read these lines by using ReadStream.
According to the documentation (1) I should receive the errors now in engine.ErrorManager.Errors, but I dont. Its empty. But also in the records I do not have all its records...

What do I wrong (2)? Or is there bug here?
Thanks in advance and best regards
Marcel

(1)https://www.filehelpers.net/example/ErrorHandling/ErrorMode.IgnoreAndContinue/#
(2)
```
var engine = new FileHelperEngine<GwrTypERecordWohnungen>();
engine.ErrorManager.ErrorMode = ErrorMode.IgnoreAndContinue;

using (var reader = new StreamReader(stream, Encoding.Default))
{
	var records = engine.ReadStream(reader);
	foreach (var err in engine.ErrorManager.Errors)
	{
		//...zero records here...
	}
}
```

PS: If you use the error-mode "ErrorMode.SaveAndContinue" then it works!

**Comment by mcavigelli** [comment]
Hoi Marcel

The documentation (1) says:

> // This wont display anything, we have dropped it

That's exactly what ErrorMode.IgnoreAndContinue should do.

Matthias
