### ISSUE TITLE
FileHelpers do not respect Range data annotation

### ISSUE THREAD

**Issue by jphellemons** [MarcosMeli/FileHelpers#366]
When parsing a (fixed width) file, the engine does not respect all data annotations

https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.rangeattribute?view=netframework-4.8

    [Range(10, 100, ErrorMessage = "Value for {0} must be between {1} and {2}.")]
    public int Weight;

I can't find any docs for this. Is this something I have to manually verify after parsing? Or what would be the best approach? And `StringLength` etc.

edit: for now I use the validator method from https://odetocode.com/blogs/scott/archive/2011/06/29/manual-validation-with-data-annotations.aspx But I was wondering if the lib would have support for this by default.

**Comment by mcavigelli** [comment]
Hi jphellemons

As you found out, the library does not support data annotations.

Assuming performance is not critical, I would do separate the deserializing and validating step.
1) read from file to list of objects (Person)
2) validating Person as described in the link you have provided.
    Having your data in an appropriate data structure will simplify the validation.

Matthias
