### ISSUE TITLE
One CSV from 3 entities

### ISSUE THREAD

**Issue by kiquenet** [MarcosMeli/FileHelpers#367]
I have 3 entities:

    public class Client
    {
         public int Indice { get; set; }
         public string Name { get; set; }
         public string Surname { get; set; }
         public string Company { get; set; }
         public string Tel1 { get; set; }
         public string Tel2 { get; set; }
    }
    
    public class CallClient
    {
         public int Indice { get; set; }
         public string CallDateTime { get; set; }
         public string Status { get; set; }
    }
    
    public class ResponsePollClient
    {
         public int Indice { get; set; }
         public string Question1 { get; set; }
         public string Question2 { get; set; }
         public string Question3 { get; set; }
         public string StatusPoll { get; set; }
    }

I have this main entity

    public class DataClient
    {
         public Client client { get; set; }
         public CallClient callClient { get; set; }
         public REsponsePollClient pollClient { get; set; }
    }

How can I use FileHelpers for generate one CSV with this fields?

> Client.Indice  
> Client.Name  
> Client.Tel1  
> CallClient.CallDateTime  
> CallClient.Status  
> ResponsePollClient.Question1  
> ResponsePollClient.Question2  
> ResponsePollClient.Question3  
> ResponsePollClient.StatusPoll

**Comment by mcavigelli** [comment]
You seem to have asked the same question on stackoverflow
https://stackoverflow.com/questions/61384115/generate-one-csv-from-main-entity-with-3-entities-as-properties

Please ask questions there, thank you, Matthias

**Comment by kiquenet** [comment]
Yeah, but not answer in SO
