### ISSUE TITLE
Multiple entries in single column

### ISSUE THREAD

**Issue by ostelaymetaule** [MarcosMeli/FileHelpers#37]
Hallo there! 
II would like to suggest a new feature. 
Assumed there are a csv File with the semicolon as a delimiter. But some of the fields includes multiple values delimited with other signs. Example:
* Alex;Kovalsky;19.02.2015;50.1
* john;Smith;04.04.2015:13.02.2014;50.1:16.3
* Max;Mustermann;;

I would expect such file to be parsed into 
```
first_name:       Alex
last_name:       Kovalsky
Checkout Date: 19.02.2015
Checkout Sum: 50.1
```
```
first_name:       john
last_name:       Smith
Checkout Date: 04.04.2015
Checkout Sum: 50.1
```
```
first_name:       john
last_name:       Smith
Checkout Date: 13.02.2014
Checkout Sum: 16.3
 ```
```
first_name:       Max
last_name:       Mustermann
Checkout Date: null
Checkout Sum: 0.0
```
Or with arrays:
```
first_name:       Alex
last_name:       Kovalsky
Checkout Date[]: {19.02.2015}
Checkout Sum[]: {50.1}
```
```
first_name:       john
last_name:       Smith
Checkout Date[]: {04.04.2015, 13.02.2014}
Checkout Sum[]: {50.1, 16.3}
```
```
first_name:       Max
last_name:       Mustermann
Checkout Date[]: {}
Checkout Sum[]: {}
```

**Comment by mcavigelli** [comment]
Hello Alexander

I don't think this is a good idea, for several reasons:
* Filehelpers is thought for "describing a class that maps to each record". With your idea you basically have two classes / records: person and checkout date.
* Having two delimiters per line will lead to conflicts: what if a name contains a ":". Is that a delimiter or a value? In case of a value, how to escape it?
* An implementation would be very complicated.

I see two possibilities for your problem:
* You do the post processing of checkout dates yourself and do a projection of person to checkout dates.
* You choose Filehelpers and save the data as master / detail data. Again the projection must be done by yourself. The master / detail approach is documented http://filehelpers.com/example_masterdetail.html and http://filehelpers.com/example_masterdetail2.html.

Do you think any of the approaches would solve your problem?

Matthias

**Comment by ostelaymetaule** [comment]
Hello Matthias,
thank you for the answer. 
I have solved this with reading the dates and the sum values into string fields and then in the AfterEvent() parse this into list<myclass> property which is marked with  [FieldNotInFile] attribute. myclass has a field defining date and a field defining double. So it looks like dictionary. 

So its kinda the first method.
Should i close the issue then?

Best regards, 
Alexander

**Comment by mcavigelli** [comment]
Hi Alexander

I have not been thinking about a solution with the AfterEvent event.
Congratulations for having solved the problem in such a FileHelper like way.

Matthias
