### ISSUE TITLE
FileHelpers.Detection.SmartFormatDetector class does not exist in .NET standard version of library

### ISSUE THREAD

**Issue by TravisEz13** [MarcosMeli/FileHelpers#370]

**Comment by mcavigelli** [comment]
Yes, that is true. It is documented in the Readme.md

> The .NET Standard FileHelpers dll currently does not contain the following features:

> Dynamic: ClassBuilder and CsvClassBuilder. ClassBuilder is difficult to maintain and a rewrite in .NET Core / Standard as is,
> would require to reference three NuGet packages. There must be better ways to write record structures at runtime.
> SmartFormatDetector: depends on ClassBuilder (Dynamic).

Maybe it was not stated clerlay enough on filehelpers.net.
We plan to add the feature in Release 4, but without code generation and reflection.

Does this information help you?

**Comment by TravisEz13** [comment]
Yeah, but the person I filed the bug for found another solution.

**Comment by kiquenet** [comment]
not solutions in 2023 ?
