### ISSUE TITLE
Docs: Move the library docs to GitHub Pages

### ISSUE THREAD

**Issue by MarcosMeli** [MarcosMeli/FileHelpers#39]
Based on the idea of @mcavigelli we will be moving the new redesigned Home GItHub pages

**Comment by mcavigelli** [comment]
The idea was in an email, so I will write down here. It might also be interesting to others:

Updating the code is thanks to github very easy and taking place every now and then. However the documentation (filehelpers.com) is still reflecting version 2. Therefore I would want to simplify the publication of the website.

I see the following requirements:
* Easy to update when software changes
  * new features
  * new releases
  * schedules
* For pull requests possibility to also add documentation, not only the code and the tests.
* Consistent layout

I propose that we use github pages for the site hosting at the moment and use it for www.filehelpers.com.

If we need an asp.net mvc hosting, we might get that with a subdomain or by changing the hosting entirely. At the moment the github pages hosting seems to be good enough.

**Comment by mcavigelli** [comment]
# Elaboration

Easy to update when ... 
  * Content could be written in a lightweight language, such as:
    * markdown
    * asciidoc
    * restructured text
    * textile

Possibility to update documentation in a pull request, when
  * all languages above seem to be viable

Consistent layout can be done with
  * a kind of templating would be helpful
    
Verification of examples (compilable examples), could be automated when:
  * including parts of real source code into documentation
  * extracting examples and make them compilable.
  
# Possible partial solutions
* restructured text and asciidoc (my personal favorite) have support to include other files. These
files can be source code, ranges are supported.
* github pages support jekyll. jekyll comes with liquid (templating system).
* Neither of restructured text or asciidoc are supported by jekyll out
  of the box.
  
# Proposed solution
* Use markdown as content language
* setup jekyll on the gh-pages branch.
* for commented examples, use markdown with custom preprocessing instructions.
  * something similar is done with ExamplesFx, I think.

**Comment by MarcosMeli** [comment]
Great !! +1 for the jekyll idea !!

Can you create the branch and setup jekyll ? I'm finishing with the material design layout to use there

I agree with markdown as language

I'm rewriting the ExamplesFx to use Roslyn, so now is easier than never to output anything we want, so I will be adding Markdown output to the library and autopublish that generate the files for all examples :)

**Comment by MarcosMeli** [comment]
I just got jekyll running on my machine, great idea !!
It perfectly fits with the old header and footer approach, we only need to rewrite some html but is not too much effort

In case that you have problems to make it run on windows here is a workaround for ruby 2.2: http://stackoverflow.com/questions/28985481/hitimes-require-error-when-running-jekyll-serve-on-windows-8-1

**Comment by MarcosMeli** [comment]
GitHub Pages up and running

http://marcosmeli.github.io/FileHelpers/

I will upload the first layout soon

**Comment by MarcosMeli** [comment]
50% Done:

The Layout
One Example
Quick Start
Home Page

Peding:

Features page
Attributes page (done but uncommited)
ChangeLog
Credits
Enhace Download Page

**Comment by mcavigelli** [comment]
Hello Marco

Thanks for the hints to get started with jekyll on my local machine:-)

The page looks very promising and easy to use!

Concerning the examples / Roslyn I had a very simple solution in mind:
* Write the text as markdown
* Include slots for source code, such as

    ```csharp
    include::relative/path/file.cs[lines=5..10]
    ```
    * (inspired by http://asciidoctor.org/docs/user-manual/#selecting-parts-of-a-document-to-include)
    * alternative: extract source code in cs files from regions
* preprocessing of those markdown files with a script
    * removes the include directive with the cs file content
    * saves the markdown file as a copy in a subdirectory

This solution sounds simpler to me and would be 
* more flexible when changing formats of the prose document (markdown, kramdown, etc.) as output
  is not compiled into a dll
* similar to asciidoc solution
* or is it to simple?

**Comment by mcavigelli** [comment]
I could start with

- [ ] ChangeLog
- [ ] Credits

**Comment by MarcosMeli** [comment]
Matthias

I lost a bit of time fighting with ruby 2.2 and other things, so glad that you avoid that :P maybe we can create a readme as a reminder in the branch

About the last comment: Great !! create the issue for these two pages and go ahead, here is a nice template for the changelog http://demo.geekslabs.com/materialize/v1.1/changelogs.html
In that case maybe is better to use html instead of markdown, like I do in attributes.html pages

About Roslyn I was thinking in the inverse, use the standard visual studio solution with ExamplesFx, parse it with Roslyn and generate the markdown pages and the exe app. 
Also the pages will contains the output generated when we ran the examples Run the examples, capture the output, can be a bit harder but has the help of visual studio writting the examples, can you provide an example for your idea to understand a bit more

Thanks for all the HELP !! after you create the credits page I will be editing it give you a ton of credit for resurect the library, fix a lot of docs and release 3.1

Best Regards

**Comment by MarcosMeli** [comment]
I'm clising this ticket and open some others for specific pages and ideas
