### ISSUE TITLE
Docs: Create ChangeLog Page

### ISSUE THREAD

**Issue by MarcosMeli** [MarcosMeli/FileHelpers#44]

**Comment by mcavigelli** [comment]
- [x] Made Jekyll work on my machine, as seen http://jekyll-windows.juthilo.com/ with ruby 2.0.
- [ ] Structuring & cleaning of kramdown content
- [ ] Applying css class to list with block attributes
      - http://kramdown.gettalong.org/quickref.html
      - http://demo.geekslabs.com/materialize/v1.1/changelogs.html

**Comment by MarcosMeli** [comment]
Near done,  3.1 and 2.0 completed
Some pending items in 3.1

www.filehelpers.net/changelog/
