### ISSUE TITLE
Docs: Create a little example walkthrough wizard

### ISSUE THREAD

**Issue by MarcosMeli** [MarcosMeli/FileHelpers#47]
For example with 3 Combos with the values

I want to: 
- Read
- Write
- Transform
- Sort
- Compare

a:
- File
- String
- Stream

with
- Delimited
- Fixed Length
- Dynamic

records

You change the combos and you get the right example

**Comment by mcavigelli** [comment]
Closing issue: documentation can be done with the example project.
