### ISSUE TITLE
Docs: Generate the Examples from the code

### ISSUE THREAD

**Issue by MarcosMeli** [MarcosMeli/FileHelpers#49]
Based on the original idea of ExamplesFx try to create the HTML of the examples from the Examples solution of the library

In the issue #39 there are some related discussions

**Comment by mcavigelli** [comment]
Thanks for giving me the opportunity to explain it better. In issue #39 some things were unclear:
> About Roslyn I was thinking in the inverse, use the standard visual studio solution with ExamplesFx, parse it with Roslyn and generate the markdown pages and the exe app.
Also the pages will contains the output generated when we ran the examples Run the examples, capture the output, can be a bit harder but has the help of visual studio writting the examples, can you provide an example for your idea to understand a bit more

The workflow could be
  1. write examples in Visual Studio and have them compiled (as it is mostly now) ie dynamic_record_example.cs.
  2. have a kramdown file per example with the explanations (no source code), dynamic_record_example.md
     1. dynamic_record_example.md has prepared (empty) code blocks, indicating the contents (csv, csharp)
     2. these code blocks contain a comment pointing to dynamic_record_example.cs (with line range, region, other)
  3. That's how is checked-in in the master branch.
  4. For updating the page a script/application comes and reads the comment in 2.ii and pulls the source code into a copy of the dynamic_record_example.md (probably an output folder).
   1. copy of dynamic_record_example.md file contains now source code
  5. copy of dynamic_record_example.md file with source code must be copied to the gh-pages branch.

This looks to me :wink: flexible (csv and csharp files can be pulled into prepared example) and similar to known solutions (as in asciidoc).

**Comment by MarcosMeli** [comment]
I just finish to generate the first deployable examples

The ExamplesFx library uses roslyn to parse the files, compile them and generate the html docs and later the tt code

http://www.filehelpers.net/examples/

**Comment by MarcosMeli** [comment]
Some examples are ok now, pending review on some others and we need to add some Excel examples
