### ISSUE TITLE
Wizard: Better type display

### ISSUE THREAD

**Issue by MarcosMeli** [MarcosMeli/FileHelpers#60]
Don't use standard framework names like System.String, etc 
Use the language specific ones: like string, int, long

**Comment by nithyanantham** [comment]
@MarcosMeli 

I am new to GitHub and i would like to work on this issue. Can you please provide me more details about this issue. By reading given description i am not able to understand the actual issue.

**Comment by mcavigelli** [comment]
Closing issue: documentation can be done with the example project.
